[opener]
edit = [
    { run = '/opt/homebrew/bin/nvim "$@"', block = true, desc = "Edit with Neovim" }
]

[open]
rules = [
    { mime = "text/*", use = "edit" },
    { mime = "application/json", use = "edit" },
    { name = "*.md", use = "edit" },
    { name = "*.txt", use = "edit" },
    { name = "*.conf", use = "edit" },
    { name = "*.toml", use = "edit" },
    { name = "*.yaml", use = "edit" },
    { name = "*.yml", use = "edit" },
]

[mgr]
# Set 'open' to use the default opener
open = "default"
